services:
  db-coursework:
    image: postgres:15
    container_name: db-coursework
    environment:
      - POSTGRES_DB=study
      - POSTGRES_USER=study
      - POSTGRES_PASSWORD=study
    ports:
      - 5433:5432
    volumes:
      - db-coursework-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U study -d study" ]
      interval: 5s
      timeout: 1s
      retries: 10
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    depends_on:
      db-coursework:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db-coursework
      - DATABASE_PORT=5432
    ports:
      - 8080:8080
      - 9090:9090
    networks:
      - backend

networks:
  backend:

volumes:
  db-coursework-data:
